# Generated by Django 4.2.19 on 2026-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_placa', models.CharField(max_length=1026, unique=True)),
                ('num_serie', models.CharField(blank=True, max_length=1024)),
                ('num_vin', models.CharField(blank=True, max_length=1024)),
                ('num_motor', models.CharField(blank=True, max_length=1024)),
                ('color', models.CharField(blank=True, max_length=1024)),
                ('marca', models.CharField(blank=True, max_length=1024)),
                ('modelo', models.CharField(blank=True, max_length=1024)),
                ('placa_vigente', models.CharField(blank=True, max_length=1024)),
                ('placa_anterior', models.CharField(blank=True, max_length=1024)),
                ('estado', models.CharField(blank=True, max_length=1024)),
                ('anotaciones', models.TextField(blank=True)),
                ('sede', models.CharField(blank=True, max_length=1024)),
                ('anio_modelo', models.CharField(blank=True, max_length=1024)),
                ('propietarios', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'de_vehiculo',
                'ordering': ['-created_at'],
            },
        ),
    ]
