# Generated by Django 4.2.19 on 2026-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentryvehiculo',
            name='num_placa',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
